%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: T:\Saison20232024.csv
%
% Auto-generated by MATLAB on 20-Oct-2024 16:41:33

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["TempsDeJeuenSec", "ButsEsprs", "Lancers"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Saison1 = readtable("datasets\Saison20232024.csv", opts);

save datasets\Saison20232024.mat Saison1

%% Clear temporary variables
clear opts